Fix/issue#14 desabilitar select
Nocs-lab/inbcm-public-frontend pull request #18
Opened 2024-08-05 04:52 UTC by thfields

desabilita o select do ano e museu em retificar.

2024-08-06 19:43 UTC, Everbero requested changes

2024-08-06 19:43 UTC, Everbero commented on src/components/Uploader.tsx
>                <Select
não poderia usar algo como {{ isRetificar && <JSX> }} aqui em vez de só desabilitar o select?

2024-08-06 19:56 UTC, thfields commented on src/components/Uploader.tsx
>                <Select
sim, inclusive corrige inserindo uma div que bloqueia o select por completo, pois o componente tem o bug que só desabilita parcialmente. o commit foi [7f32128](https://github.com/Nocs-lab/inbcm-public-frontend/commit/7f32128d2377040505d489cf527edefebd1273f4)

2024-08-07 16:21 UTC, Everbero commented on src/components/Uploader.tsx
>                <Select
@thfields não seria melhor fazer algo assim? Se o select vai estar desativado é não exibi-lo, pq se renderizar o componente não daria para mudar o html dele pelo inspetor? Assim não precisaria adicionar esta div que vc colocou em volta.

```js
    {{ !isRetificar && <Select .../>}}
```

2024-08-08 02:36 UTC, thfields commented
fiz a alteração que pediu, quando o uploader é aberto pelo retificar, o select do ano e do museu não são carregados. Em compensação, inseri no componente Retificar o id da declaração e o ano com o museu embaixo como textos para o usuário ficar identificando qual a declaração que está sendo retificada. também alterei o caminho do botão de "voltar" pois voltando para a tela inicial estava dificultando o trabalho e seria ideal que ele voltasse para tela anterior (o index da declaração) e sabendo que já tem o botão "Cancelar" que já vai até a página inicial. o commit foi: e4fa6f65ddf44d89d504c815054e4c9ab00170a6

2024-08-08 12:11 UTC, Everbero approved these changes

2024-08-08 12:11 UTC, Everbero approved these changes

2024-08-08 12:12 UTC, merged

2024-08-08 12:12 UTC, Everbero commented
Closes #18