Task/204
Nocs-lab/inbcm-public-frontend pull request #4
Opened 2024-06-17 20:36 UTC by vadolasi

Também arruma a #3

2024-06-18 15:29 UTC, Everbero approved these changes

2024-06-18 15:30 UTC, Everbero approved these changes

2024-06-18 15:39 UTC, Everbero requested changes

2024-06-18 15:39 UTC, Everbero commented on src/parseXLSX.ts
Adicione comentários explicando a utilidade, entrada e retorno dos métodos.

2024-06-18 15:39 UTC, Everbero commented on package.json
Não sei se entendi corretamente mas o projeto INNCM é usado para buildar o parse-xlsx?

2024-06-18 20:01 UTC, vadolasi commented on package.json
Sim, mas como para fazer isso é necessário ter o Rust instalado eu estava buildando na minha máquina e mandando os arquivos compilados pro repositório. Pois nesse caso os arquivos compilados são compatíveis com qualquer browser.

Caso seja definido que o Rust será utilizado para fazer o parser das planilhas, coloco instruções de como fazer a compilação. Mas no momento vou voltar utilizar a versão em JS para tentar fazer algumas otimizações.

2024-06-19 18:23 UTC, Everbero approved these changes

2024-06-19 18:23 UTC, merged